# ============================================================
# SwiftLint Configuration - MarvelApp (SwiftUI + Modular SPM)
# ============================================================

included:
  - Modules
  - MarvelApp

excluded:
  - "**/.build/**"
  - "**/.swiftpm/**"
  - "**/DerivedData/**"
  - "**/Tests/**"
  - "**/TestUtils/**"
  - "**/Documentation/**"
  - "**/Scripts/**"
  - "**/Generated/**"
  - "**/checkouts/**"
  - "**/Pods/**"
  - "**/Package.swift"

# ============================================================
# Desativadas (falsos positivos em SwiftUI)
# ============================================================
disabled_rules:
  - explicit_init
  - type_body_length
  - array_init
  - nesting
  - number_separator
  - multiple_closures_with_trailing_closure

# ============================================================
# Regras ativadas
# ============================================================
opt_in_rules:
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - file_header
  - first_where
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - strict_fileprivate
  - trailing_whitespace
  - vertical_whitespace
  - return_arrow_whitespace
  - redundant_string_enum_value
  - implicit_optional_initialization
  - mark
  - todo
  - comment_spacing
  - multiple_closures_with_trailing_closure

# ============================================================
# Regras de análise profunda
# ============================================================
analyzer_rules:
  - unused_import

# ============================================================
# Limites e formatação
# ============================================================
file_length:
  warning: 400
  error: 600

function_parameter_count:
  warning: 5
  error: 7

function_body_length:
  warning: 100
  error: 150

line_length:
  warning: 250
  error: 300

type_name:
  max_length: 50

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 50

unused_import:
  always_keep_imports: [Foundation, SwiftUI, UIKit]
  severity: warning

# ============================================================
# Custom Rules
# ============================================================
custom_rules:
  unknown_case_representable:
    name: "Unknown Case Representable"
    regex: "(?-s)enum.* (Codable|Decodable)(?!.*UnknownCaseRepresentable)"
    message: "Implement UnknownCaseRepresentable on Decodable enums"
    severity: error

  swiftui_view_suffix:
    name: "SwiftUI View Naming"
    regex: 'struct\\s+[A-Z][A-Za-z0-9]*(?<!View)\\s*:\\s*View'
    message: "SwiftUI View structs devem terminar com 'View'."
    severity: warning

# ============================================================
# Ajustes gerais
# ============================================================
trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 1

todo:
  severity: warning
